mickys/urls.py
from django.conf.urls import url
from mickys import views
from django.urls import path

app_name = 'mickys'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
]

mickysbite/urls.py
from django.contrib import admin
from django.urls import path, include
from mickys import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('mickys/', include('mickys.urls')),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special')
]

mickys/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class UserProfile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    mobile_number = models.IntegerField()

    def __str__(self):
        return self.user.username


class Product(models.Model):
    product_name = models.CharField(max_length=100, blank=True)
    product_price = models.IntegerField()
    product_description = models.CharField(max_length=200, blank=True)
    date_added = models.DateTimeField()

    def __str__(self):
        return self.product_name

mickys/forms.py
from django import forms
from django.contrib.auth.models import User
from mickys.models import UserProfile


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'first_name','last_name', 'email', 'password')


class UserProfileForms(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('mobile_number',)


class ProductForm(forms.ModelForm):
    class Meta:
        fields = '__all__'

mickys/views.py
from django.shortcuts import render
from .models import UserProfile, Product
from django.contrib.auth.models import User
from .forms import UserForm, UserProfileForms, ProductForm
from django.shortcuts import redirect, get_object_or_404

from django.contrib.auth import authenticate, logout, login
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.

def index(request):
    return render(request, 'mickys/index.html')

@login_required()
def special(request):
    return HttpResponseRedirect('Logged in!')

@login_required()
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        user_profile = UserProfileForms(data=request.POST)

        if user_form.is_valid() and user_profile.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = user_profile.save(commit=False)
            profile.user = user
            profile.save()

            registered = True

        else:
            print(user_form.errors, user_profile.errors)
    else:
        user_form = UserForm()
        user_profile = UserProfileForms()

#    context ={'user_form': user_form, 'user_profile':user_profile, 'registered':registered}

    return render(request, 'mickys/registration.html',
                  {'user_form': user_form, 'user_profile':user_profile, 'registered':registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse('Account not active')
        else:
            print('someone tried to login and failed')
            print('Username: {} and password {}'.format(username, password))

            return HttpResponse('invalid details')
    else:
        return render(request, 'mickys/login.html', {})



def get_product(request):
    all_product = Product.objects.all()
    context = {'all_product': all_product}

    return render(request, '', context)


def create_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('#product_home_page')

        else:
            form = ProductForm()
            context = {'form':form}
            return render(request, 'add_product_page', context)


def update_product(request):
    product = get_object_or_404(Product, pk=id)
    if request.method == 'POST':
        form = ProductForm(request.POST, instance=product)
        if form.is_valid():
            form.save()
            return redirect('Product page')

    else:
        form = ProductForm(instance=product)
        context = {'form':form}
        return render(request, 'update_product', context)


def delete(request):
    product = get_object_or_404(Product, pk=id)
    product.delete()

    return redirect('product page')

templates/mickys/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <ul>
        <li><a href="{%url 'index'%} ">MicksyBite</a></li>
        <li><a href="{% url 'admin:index'%} ">Admin</a></li>
        <li><a href="{%url 'mickys:register'%} ">Register</a></li>
        {%  if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a> </li>

         {% else %}

             <li><a href="{% url 'mickys:user_login' %}">Login</a> </li>
        {% endif %}

    </ul>
</body>
</html>

templates/mickys/index.html
{% extends "mickys/base.html" %}
{% block body_block %}

<div class="jumbotron">
    <h3>MickysBite</h3>
</div>
{% endblock %}

templates/mickys/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form action="{% url 'mickys:user_login' %}" method="post">
{% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter Username">

    <label for="password">Password:</label>
    <input type="text" name="password">

    <input type="submit" name="" value="Login">
</form>

</body>
</html>

templates/mickys/registration.html
{#{% extends "mickys/base.html" %}#}
{#{% load staticfiles %}#}
<!DOCTYPE html>
<html lang="en">

<body>

{% block body_block %}

<div class="jumbotron">
    {% if registered %}
        <h3>Thank you</h3>
    {% else %}
        <h1>Register here</h1>
        <h3>Fill form below</h3>

        <form enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ user_profile.as_p }}
            <input type="submit", name="", value="Register">
        </form>
    {% endif %}
</div>


{% endblock %}
</body>